"""Convert the pinned Natural Earth GeoJSON to local QML outlines, offline."""

import hashlib
import json
import math
import sys
from pathlib import Path

source = Path(sys.argv[1]).read_bytes()
expected = "6866c877d39cba9c357620878839b336d569f8c662d3cfab4cb1dbe2d39c977f"
if hashlib.sha256(source).hexdigest() != expected:
    raise SystemExit("Unexpected Natural Earth input checksum")

# The 1:110m source is already generalized. Keep every exterior vertex; omit
# holes and attributes because the prototype draws outlines, not filled regions.
rings = []
for feature in json.loads(source)["features"]:
    geometry = feature["geometry"]
    polygons = geometry["coordinates"]
    if geometry["type"] == "Polygon":
        polygons = [polygons]
    for polygon in polygons:
        rings.append([[round(x, 3), round(y, 3)] for x, y in polygon[0]])


def contains(lon, lat, ring):
    inside = False
    previous = ring[-1]
    for current in ring:
        x1, y1 = previous
        x2, y2 = current
        if (y1 > lat) != (y2 > lat) and lon < (x2 - x1) * (lat - y1) / (y2 - y1) + x1:
            inside = not inside
        previous = current
    return inside


# Precompute land stippling once, offline. Latitude-dependent longitude spacing
# keeps dots approximately uniform on the sphere rather than crowding the poles.
bounded = [
    (min(x for x, _ in r), min(y for _, y in r),
     max(x for x, _ in r), max(y for _, y in r), r)
    for r in rings
]
dots = []
for band in range(-59, 60):
    lat = band * 1.5
    step = 1.5 / max(0.1, math.cos(math.radians(lat)))
    for column in range(math.ceil(360 / step)):
        lon = -180 + column * step
        if any(
            x1 <= lon <= x2 and y1 <= lat <= y2 and contains(lon, lat, ring)
            for x1, y1, x2, y2, ring in bounded
        ):
            dots.append([round(lon, 3), round(lat, 3)])

markers = []
for feature in json.loads(source)["features"]:
    properties = feature["properties"]
    code = properties["ISO_A2_EH"]
    # Natural Earth provides ISO exceptions for France/Norway and XK for Kosovo.
    # Features without a two-letter code have no invented country mapping.
    if len(code) == 2:
        markers.append({"code": code, "name": properties["NAME_EN"],
                        "lon": round(properties["LABEL_X"], 3),
                        "lat": round(properties["LABEL_Y"], 3)})
markers.sort(key=lambda item: item["code"])

target = Path(__file__).resolve().parents[1] / "assets" / "Countries.js"
target.parent.mkdir(exist_ok=True)
target.write_text(
    "// Generated by tools/prepare_geometry.py. Natural Earth, public domain.\n"
    "// See assets/NOTICE.md for source and checksum.\nvar outlines = "
    + json.dumps(rings, separators=(",", ":"))
    + ";\n"
    + "var markers = " + json.dumps(markers, separators=(",", ":")) + ";\n"
    + "var landDots = " + json.dumps(dots, separators=(",", ":")) + ";\n"
)
print(f"Wrote {len(rings)} outlines, {sum(map(len, rings))} points, {len(dots)} land dots")
