"""Convert the pinned Natural Earth GeoJSON to local QML outlines, offline."""

import hashlib
import json
import sys
from pathlib import Path

source = Path(sys.argv[1]).read_bytes()
expected = "6866c877d39cba9c357620878839b336d569f8c662d3cfab4cb1dbe2d39c977f"
if hashlib.sha256(source).hexdigest() != expected:
    raise SystemExit("Unexpected Natural Earth input checksum")

# The 1:110m source is already generalized. Keep every exterior vertex; omit
# holes and attributes because the prototype draws outlines, not filled regions.
rings = []
for feature in json.loads(source)["features"]:
    geometry = feature["geometry"]
    polygons = geometry["coordinates"]
    if geometry["type"] == "Polygon":
        polygons = [polygons]
    for polygon in polygons:
        rings.append([[round(x, 3), round(y, 3)] for x, y in polygon[0]])
target = Path(__file__).resolve().parents[1] / "assets" / "Countries.js"
target.parent.mkdir(exist_ok=True)
target.write_text(
    "// Generated by tools/prepare_geometry.py. Natural Earth, public domain.\n"
    "// See assets/NOTICE.md for source and checksum.\nvar outlines = "
    + json.dumps(rings, separators=(",", ":"))
    + ";\n"
)
print(f"Wrote {len(rings)} outlines, {sum(map(len, rings))} points")
